# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here

import numpy as np

print(np.__version__)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1

a = np.random.random((2,3,5))
print(a)

[[[0.74069388 0.38433112 0.10397888 0.18478458 0.24673963]
  [0.12190424 0.98033358 0.91607414 0.99717999 0.63584645]
  [0.78128958 0.29689699 0.24975485 0.80531296 0.36142671]]

 [[0.47489462 0.28014345 0.20326961 0.03981962 0.434348  ]
  [0.15400515 0.28338208 0.54666194 0.50196405 0.12947116]
  [0.36442205 0.74571474 0.34583262 0.94909323 0.8217358 ]]]


In [8]:
# Method 2

a = np.random.rand(2,3,5)
print(a)

[[[0.37674114 0.0727033  0.33013306 0.80704053 0.60145958]
  [0.59951141 0.19418142 0.0668133  0.11934796 0.86970367]
  [0.34859486 0.55737893 0.9986331  0.47554747 0.09247199]]

 [[0.45872451 0.66833235 0.39526661 0.24628942 0.14482382]
  [0.36623609 0.43309124 0.52336101 0.38130475 0.33730227]
  [0.68993293 0.74324204 0.60564764 0.46049014 0.22054047]]]


In [11]:
# Method 3

np.random.seed(1)
np.random.randn(2,3,5)

array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,
          0.86540763],
        [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 ,
         -0.24937038],
        [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,
          1.13376944]],

       [[-1.09989127, -0.17242821, -0.87785842,  0.04221375,
          0.58281521],
        [-1.10061918,  1.14472371,  0.90159072,  0.50249434,
          0.90085595],
        [-0.68372786, -0.12289023, -0.93576943, -0.26788808,
          0.53035547]]])

#### 4. Print *a*.


In [ ]:
# your code here

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here

#array should be 5x3x2

b =  np.full((5,3,2),1)

print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 6. Print *b*.


In [ ]:
# your code here

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [13]:
# your code here

print(a.size)
print(b.size)

if a.size == b.size:
    print("a and b are same size")
else:
    print("a and b not same size")

30
30
a and b are same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [14]:
print(a.shape)
print(b.shape)


if a.shape == b.shape:
    print('TRUE')
else:
    print('FALSE')

(2, 3, 5)
(5, 3, 2)
FALSE


In [ ]:
# your answer here

no because they have a different shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [15]:
# your code here

c = b.transpose()

print(c)
print(c.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [34]:
# your code/answer here

d = a + c

print(d)

print(d.shape)

[[[1.37674114 1.0727033  1.33013306 1.80704053 1.60145958]
  [1.59951141 1.19418142 1.0668133  1.11934796 1.86970367]
  [1.34859486 1.55737893 1.9986331  1.47554747 1.09247199]]

 [[1.45872451 1.66833235 1.39526661 1.24628942 1.14482382]
  [1.36623609 1.43309124 1.52336101 1.38130475 1.33730227]
  [1.68993293 1.74324204 1.60564764 1.46049014 1.22054047]]]
(2, 3, 5)


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here

#a is 2x3x5
# d is 2x3x5

print(a)
print(d)

#the relation in arrays is the same, two sets of 3 rows and 5 columns

[[[0.37674114 0.0727033  0.33013306 0.80704053 0.60145958]
  [0.59951141 0.19418142 0.0668133  0.11934796 0.86970367]
  [0.34859486 0.55737893 0.9986331  0.47554747 0.09247199]]

 [[0.45872451 0.66833235 0.39526661 0.24628942 0.14482382]
  [0.36623609 0.43309124 0.52336101 0.38130475 0.33730227]
  [0.68993293 0.74324204 0.60564764 0.46049014 0.22054047]]]
[[[1.37674114 1.0727033  1.33013306 1.80704053 1.60145958]
  [1.59951141 1.19418142 1.0668133  1.11934796 1.86970367]
  [1.34859486 1.55737893 1.9986331  1.47554747 1.09247199]]

 [[1.45872451 1.66833235 1.39526661 1.24628942 1.14482382]
  [1.36623609 1.43309124 1.52336101 1.38130475 1.33730227]
  [1.68993293 1.74324204 1.60564764 1.46049014 1.22054047]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here

e = a*c

print(e)

[[[0.37674114 0.0727033  0.33013306 0.80704053 0.60145958]
  [0.59951141 0.19418142 0.0668133  0.11934796 0.86970367]
  [0.34859486 0.55737893 0.9986331  0.47554747 0.09247199]]

 [[0.45872451 0.66833235 0.39526661 0.24628942 0.14482382]
  [0.36623609 0.43309124 0.52336101 0.38130475 0.33730227]
  [0.68993293 0.74324204 0.60564764 0.46049014 0.22054047]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [19]:
# your code/answer here

if e.any() == a.any():
    print('TRUE')
else:
    print('FALSE')

TRUE


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
# your code here

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.998633096835238
1.0668133014962284
1.4394949010265254


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
# your code here

f = np.empty((2,3,5))

print(f)

[[[0.37674114 0.0727033  0.33013306 0.80704053 0.60145958]
  [0.59951141 0.19418142 0.0668133  0.11934796 0.86970367]
  [0.34859486 0.55737893 0.9986331  0.47554747 0.09247199]]

 [[0.45872451 0.66833235 0.39526661 0.24628942 0.14482382]
  [0.36623609 0.43309124 0.52336101 0.38130475 0.33730227]
  [0.68993293 0.74324204 0.60564764 0.46049014 0.22054047]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here
def func():
    for i in d:
        if d_mean < i > d_min:
            f = 25
        if d_mean < i > d_max:
            f = 75
        if d_mean == i:
            f = 50
        if d_min == i:
            f = 0
        if d_max == i:
            f = 100
            
func()

    

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [52]:
    for i,array1 in enumerate(d):
        for x,array2 in enumerate(array1):
            for y,array3 in enumerate(array2):
                if array3 > d_min and array3 < d_mean:
                    f[i][x][y] = 25
                if array3 > d_mean and array3 < d_max:
                    f[i][x][y] = 75
                if d_mean == array3:
                     f[i][x][y] = 50
                if d_min == array3:
                     f[i][x][y] = 0
                if d_max == array3:
                     f[i][x][y] = 100    
        

In [53]:
f

array([[[ 25.,  25.,  25.,  75.,  75.],
        [ 75.,  25.,   0.,  25.,  75.],
        [ 25.,  75., 100.,  75.,  25.]],

       [[ 75.,  75.,  25.,  25.,  25.],
        [ 25.,  25.,  75.,  25.,  25.],
        [ 75.,  75.,  75.,  75.,  25.]]])

In [58]:
x = [10,434,343,452,5252]

#for index, value in enumerate(list)

for i, m in enumerate(x):
    print(i,m)

0 10
1 434
2 343
3 452
4 5252


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here

# 