In [ ]:
# ENCODING EXAMPLES

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
values = np.array(data)
values = values.reshape(len(values), 1)
onehot_encoded = onehot_encoder.fit_transform(values)
print(onehot_encoded)

lb = LabelBinarizer()
print(lb.fit_transform(data))  # IT CAN TAKE THE ARRAY DIRECTLY

###################################################################################

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
pd.set_option('display.max_columns', 100)
data = pd.read_csv('Customer-Churn.csv')
# print(data.head(2))
print(data.columns)
print(data.shape)
# binary classification model


X = data[['tenure', 'SeniorCitizen', 'MonthlyCharges']]
Y = np.array(data['Churn'])
model = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr')
classification = model.fit(X, Y)    # FITTING A MODEL WITHOUT SCALING
print(classification.score(X, Y))
probabilities = classification.predict_proba(X) # func of probability


from sklearn import preprocessing
x_scaled = preprocessing.scale(X)
# print(x_scaled.shape)
from sklearn.preprocessing import Normalizer
transformer = Normalizer().fit(X)
x_normalized = transformer.transform(X)
# print(x_normalized.shape)
from sklearn.preprocessing import StandardScaler
transformer = StandardScaler().fit(X)
x_standardized = transformer.transform(X)
# print(x_standardized.shape)
model = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr')
classification = model.fit(x_standardized, Y)
print(classification.score(x_standardized, Y))
#
model = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr')
classification = model.fit(x_normalized, Y)
print(classification.score(x_normalized, Y))
model = LogisticRegression(random_state=0, solver='lbfgs', multi_class='ovr')
classification = model.fit(x_scaled, Y)
print(classification.score(x_scaled, Y))
probabilities = classification.predict_proba(x_scaled)
# print(probabilities[:, 1])    #The returned estimates for all classes are ordered by the label of classes
# In this data, class "NO" is represented first in Y. Hence the 'probabilites' variable has its first
# value represents probability for 'NO'
print(probabilities)
# print(len(Y))
# print(len(probabilities))

THRESHOLD = 0.5 # you set it, by default is .5
preds = np.where(probabilities[:, 1] > THRESHOLD, 1, 0)
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, roc_auc_score, precision_score
Y_nums = np.where(data['Churn'] == 'Yes', 1, 0)
print(accuracy_score(Y_nums, preds))

print(probabilities[:, 1][:10])
print(probabilities[:10])
print(Y_nums[:10])
print(Y[:10])
print(preds[:10])

# ROC CURVE

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt
probabilities_positives = probabilities[:, 1]
lb = LabelBinarizer()
Y_binary = lb.fit_transform(Y)
lr_auc = roc_auc_score(Y_binary, probabilities_positives) # 2 arguments- the actual values & probabilities
fpr, tpr, thresholds = roc_curve(Y_binary, probabilities_positives)
plt.plot(fpr, tpr, marker='.', label='Logistic')
x_plot = np.arange(0, 1, 0.1) # to make 45 degree line
plt.plot(x_plot, x_plot, marker='*', label='Main diagonal') # to make 45 degree line
# linestyle = '--'
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend()
plt.show()

# measure accuracy on test data

In [1]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)
print(integer_encoded)

[0 0 2 0 1 1 2 0 2 1]


In [ ]:
# it's just one list. not a list inside a list. think abobut it in a dataframe

In [3]:
# 

import numpy as np 

onehot_encoder = OneHotEncoder(sparse=False)
values = np.array(data)
values = values.reshape(len(values), 1)
onehot_encoded = onehot_encoder.fit_transform(values)
print(onehot_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [4]:
# label binarizer

lb = LabelBinarizer()
print(lb.fit_transform(data))  # IT CAN TAKE THE ARRAY DIRECTLY

[[1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]]
